def count_nt(sequence):
    counts = []
    bases = ['A', 'C', 'G', 'T']
    for base in bases:
        counts.append(sequence.count(base))

    print "{} {} {} {}".format(*counts)

    return {b:c for b, c in zip(bases, counts)}

if __name__ == '__main__':
    count_nt('GGGAACTCCTCGGTCGCCACAGGCGTCTGGCGGCCCGCAGAAGTCCATATTGGGAGATTGAGCCTAACCTGTACCTGTCTCATCAACAACCTAAAAGAGTTGATTCAGAGAAGAGTTTCATTTCTAAGACTCGGTTGACCCTCCCTATTTCAGTGATAATCAGTGCGTAAGCCGTAAAAGCGAATCGCAATTCCTATCGTACGCGACTCCCGCCCGTTGCGTTTACGAAGAGATGATGAATACGATTTAGCTACGGTTCATTTCTTTAACAACGTGCCGAGATGAACAAAGGTCCGGATAACGGTACCCCGTCATGTCTGTCACGCCCTACCGCCGGATAGGTATGGTGCAACAGCCTGTTCGTTTTCGACCTTGGACCGGAGCCAGATGTTCAGTGCTGTGGTACAACACAACTCAAGCCGTTCGAGTGATCTAGTCGCCTCCCAGCGGCCAAGTGACGGGGTCACAGCCTGAGTCTCTTGATGCGATGAAGTACGCTTATTACAGGCAACACGGGGCTATATGGGTTCATAGATGATTCAACGTGAATCGCAAAGTTTAGCGCTGACAACTGCGTCACATGCCTCATAGGACGTAGCCCGATGACAGTATGGTGATCCGCCATGCACTTGCTATAATGGGTCGAAGGGTTCGCCAGGTTAGCGTCGTTGACGGAAGAAAGAATATCGTGTACGCGATTGATCCCAACGTACGACTCTCCGTTACCCGCAGTGCCGACATAGTAGTGGAATCGGGACGTACAAGGCACCCGAGGCCCTATAAACGTCTAGTGTACTCTATCACGGAATATGTTCTGCGGGCCCTCGGCCAAACGTAGTCTGCTCTGGG')
