def find_motif(subsequence, sequence):
    base_index = 1
    locations = []
    while True:
        index = sequence.find(subsequence)
        if index != -1:
            base_index += index + 1
            sequence = sequence[index+1:]
            locations.append(base_index-1)
        else:
            break
    return locations

if __name__ == '__main__':
    print ' '.join([str(i) for i in find_motif('CACTTATCA', 'GTTCACTTATTCGGTCACTTATTCACTTATGCACTTATCACTTATTTACACTTATCACTTATAGCACTTATCACTTATCAACACCCACTTATCCCACTTATTTCCACTTATTCACTTATGTGTTCTTGAACACTTATTGACACTTATTATCACTTATACTCACTTATGCCACTTATCACTTATCACACTTATTAATGACACTTATTCTGCCCACTTATCACTTATTCACCACTTATTTCACTTATCTGCACTTATCACTTATCACTTATCACTTATGCGACACTTATCCGGCACTTATTCACACTTATCCCTTACACTTATGACTCGACACTTATACACTTATTCACTTATCACTTATGTCACTTATGCCACTTATGTGCCCAGCGCACTTATCCCACTTATGCACTTATCGCACTTATTCTGGGCACTTATTCATAACGGCACACTTATCACTTATGAATTCACTTATCACTTATGCCACTTATAAACACTTATCACTTATCTTGACAACACTTATGCACTTATAGCGACACTTATGGCATGGCACTTATCACTTATACTCGTGACACTTATATCGGCACTTATCCACTTATACACTTATAGGCACTTATCTCACTTATAGGACACTTATTGCAAGAGGCCACTTATTTCTACACTTATCACTTATCACTTATCACTTATGCCATACACTTATCACTTATCACTTATCACTTATAGATCGCACTTATGCGACAGCATACCACTTATCACTTATGCCCACTTATGGTCACTTATACACTCACTTATAGGACACGAGTCACTTATTGCTCACTTATGCACTTATTAGATTACACTTATCACTTATCTGCACTTATACGTGTCACTTATGAGACGCACTTATACCACTTATATGGCCACTTATGACACTTATAGCACTTATTCACTTATCACTTATATAACCACTTATGCACTTATCCCGGCCACTTATA')])
