from translate import translation_map

reverse_map = dict()

for key, value in translation_map.items():
    if value not in reverse_map.keys():
        reverse_map[value] = [key]
    else:
        reverse_map[value].append(key)

def reverse_translation_space(sequence, mod):
    ways = 1
    for amino_acid in sequence:
        ways *= len(reverse_map[amino_acid])
        ways %= mod

    ways*= len(reverse_map['Stop'])
    return int(ways % mod)

if __name__ == '__main__':
    print reverse_translation_space('MRMHDECWVLSERSINSPWLCVTVMFCQCMRRYLTCICMIMELNWTMMNTNNFFHKWWNQYFHPPRLYGRYQTMVTGWLTAFCQAEHDSDMMSLIKCDFMDLQALGIQQFNNMRHLEGTFIWVGVYPQPAWFCWRRWPHQPLWKPWLHCMFLGITKDKDLGQHTARNDRDTYSGRCHCQHMNWYPGKWTTKAHHRQGKAEYYYDFWYHPIQAIEFANAQCPFMHMKLLEWAYHFQAKNANGEKWLDEIELRPTPKPNRQKPEISTVNKWPMHWKSHLKACTLVDPYTTPHSDYEFHFISNFNYEGQEVGHWLRGYCYAHECSYVHKYMFYINLCVTACQGDLAVMWLSMLNTQLEIAVRILSTLAVVIWAITLRYVSYSQENYSNPKVGAFCPYRLFNMCQKFEFKNFSVKAHQKMWSNMAIHADLMLDNQRVSIVGHIKGTNSSDMKMSTWTTHQQDCTGPAASQSWTGIHIDYCHSCNFWISFAQRVQGHHIAVFNKIWAIRMTNWNLYNSSSCEEMQMNFCLANVQYWQAWRDILPLEGMQEDMWMNQITISGDRERFEEWYLWEWSGVKLYDTFHYHYARRSTNIAPKEYESQMILRAPEINIHTQTTEWTNAYNPVRQCRYQWMYFARYKDLFCNCIHNSMLQWEHTAPGVQCEWGHDQLNLHDKMNDMFSEYVQKHKNWLKGDCEIVFLYNFTCIQSPFYHAEDIMQRQWHQKNPDTRWCKRVPEGHVHTARCYFEPAIRPHFGAKYYSASTQKDKRHMYQRYGGQVAQPYVETKHKCRECNRHGDGMCFTQDAHIPCPMLMMPCRDAEWCTLGIYSAHQTPGWSLKEFCFSHIQDHLFEIPFQVTFVWYHRFMNYQIKLAEILPSFELSVHKYVKLTSDWLCLATDYPFFMGQQKATCQFIQDKSKFVCTHIQWVTMPSQRFIEAQSAWSEMQNLMCQVGTTGNCADFDETNDTLSIIENFQQYMSHIMPTYPTNVVMLCCQFFTGRWLMI', 1e6)
